#!/bin/bash
#********************************************************
#Author    : Adriano ALves aalves3
#Date      : Oct/01/2015
#File Name : create_acct
#Objective : HW2 CS155B
#            This script will create accounts for mySQL
#             with options:
#                -l to read user names from a file
#                -h for help
#
#********************************************************
# to change dafault password just change in the following
# line
#**********  passwords *********#
userpswd="changeme"
mysqlpswd="greenLight"
#*********************** help() *************************
myhelp()
{
   echo $'\nThis Program create accounts for mySQL\n'
   echo $'create_acct <user_id1> <user_id2> ...'
   echo $'options: -f <file_name> [to read users name from a file]'
   echo $'         -h [for help]\n'
}
#********************** errormsg() **********************
errormsg()
{
   echo -e -n "\r\033[31m"
   echo "usage:create_acct user_id1 user_id2 ..."
   echo "options:"
   echo " -f <file_name> <user_id1> <user_id2> ..."
   echo " -h [for help]"
   echo -e -n "\033[0m"
}
#********************** domysql() ***********************
domysql()
{
   mysql -BcNns --disable-pager -u root -p$mysqlpswd <<-EOF
   $@;
EOF
}
#********************** RUroot() ************************
RUroot()
{
    x=$(id | grep '(root)')

    if [ -z "$x" ];then
        echo "false"
    else
        echo "true"
    fi
}
#********************** readFile() ***********************
readFile()
{
   #check if is a valid fale name
   if [ -f "$1" ];then
      #reading file
      while read line;do
      #check if user exist
      x=$(./showusers | grep "$line")

        if [ -z "$x" ];then
           domysql "create user '$line'@'localhost' identified by '$userpswd';"
           echo "Account created for :"$line
        else
           echo "user already exist :"$line
        fi
      done < "$1" 
   else 
      echo -e "\033[41m invalid file name :\033[0m"$1
   fi
}
#********************** readFile() ***********************
mkacct()
{
   for userid in "$@"; do
       #check if user exist
       x=$(./showusers | grep "$userid")

       if [ -z "$x" ];then
          domysql "create user '$userid'@'localhost' identified by '$userpswd';"
          echo "Account created for :"$userid
       else
          echo "user already exist :"$userid
       fi
   done
}
#********************* checking user ********************
if [ $(RUroot) = 'false' ];then
    echo -e -n "\r\033[41m"
    echo -e "PERMISSION DENIED!\033[0m"
    echo    "root access only"
    exit 1
else
#  clear
  #******************** NO argument **********************
  if (($# == 0));then
     errormsg
  else
    #******************** option -h **********************
     if [[ $1 = "-h" || $1 = "-H" ]];then
         if (($# == 1));then
             myhelp
         else 
             errormsg
         fi
     #****************** option -f ***********************
     elif [[ "$1" = "-f" || "$1" = "-F" ]];then
        readFile $2
        # getting args after file name
        mkacct ${@:3}
     #****************** if no optiom ********************
     elif [[ $1 != *"-"*  ]];then
        mkacct $@
     else 
        errormsg
     fi
  fi
fi
#*** END ***#

